CIHelper.checkCommits: avoid unnecessary `Promise.all()`
The function that is run on each commit is not `async` and therefore
does not need to be awaited, either.

This will be pointed out by `typescript-eslint` v8.45.0, with the
following symptom:

  lib/ci-helper.ts
  Error:   1023:17  error  Unexpected iterable of non-Promise
    (non-"Thenable") values passed to promise aggregator
    @typescript-eslint/await-thenable

So let's avoid that problem before upgrading.

Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>